# Generated by Django 4.1 on 2022-09-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterField(
            model_name="profile",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
