# Generated by Django 4.0.6 on 2022-10-01 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-is_read', '-created']},
        ),
    ]
