# Generated by Django 4.2.2 on 2023-07-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_profile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="short_bio",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
