# Generated by Django 4.2.2 on 2023-07-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_profile_short_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="short_bio",
            field=models.TextField(max_length=200),
        ),
    ]
