# Generated by Django 4.2.2 on 2023-08-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_profile_short_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="social_linkedin",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="social_patreon",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="social_twitch",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="social_website",
        ),
    ]
