# Generated by Django 4.1 on 2022-09-03 19:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mod",
            fields=[
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("created", models.TimeField(auto_now_add=True)),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, default="default.png", null=True, upload_to=""
                    ),
                ),
                ("download_link", models.CharField(max_length=2000)),
                ("vote_total", models.IntegerField(blank=True, default=0, null=True)),
                ("vote_ration", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("name", models.CharField(max_length=200)),
                ("created", models.TimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("created", models.TimeField(auto_now_add=True)),
                ("body", models.TextField(blank=True, max_length=200, null=True)),
                (
                    "value",
                    models.CharField(
                        choices=[("up", "Up Vote"), ("down", "Down Vote")],
                        max_length=200,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "mod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="projects.mod"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mod",
            name="tags",
            field=models.ManyToManyField(blank=True, to="projects.tag"),
        ),
    ]
