# Generated by Django 4.1 on 2022-09-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_mod_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mod",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterField(
            model_name="mod",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
