# Generated by Django 4.1 on 2022-09-10 15:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_review_owner_alter_review_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mod",
            options={"ordering": ["-vote_total", "-vote_ration", "-title"]},
        ),
    ]
