# Generated by Django 4.2.1 on 2023-05-29 23:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_remove_mod_created_alter_mod_download_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mod",
            old_name="download_link",
            new_name="modfile",
        ),
    ]
