# Generated by Django 4.2.2 on 2023-07-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_alter_mod_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="mod",
            name="short_intro",
            field=models.TextField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
