# Generated by Django 4.2.2 on 2023-07-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_alter_mod_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="mod",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
