# Generated by Django 4.2.2 on 2023-07-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0013_mod_short_intro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mod",
            name="short_intro",
            field=models.TextField(max_length=150),
        ),
    ]
