# Generated by Django 4.2.2 on 2023-07-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0014_alter_mod_view_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mod",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
    ]
