# Generated by Django 4.2.2 on 2023-07-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_alter_mod_short_intro"),
        ("projects", "0015_alter_mod_view_count"),
    ]

    operations = []
