# Generated by Django 4.2.2 on 2023-07-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_merge_20230726_1814"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mod",
            name="short_intro",
            field=models.TextField(max_length=200),
        ),
    ]
