# Generated by Django 4.2.2 on 2023-07-27 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0017_alter_mod_short_intro"),
    ]

    operations = [
        migrations.AddField(
            model_name="mod",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mod",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
