# Generated by Django 4.2.2 on 2023-07-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_mod_created_mod_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="mod",
            name="version",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
    ]
