# Generated by Django 4.2.2 on 2023-08-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0019_mod_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="title",
            field=models.ImageField(
                blank=True, max_length=200, null=True, upload_to=""
            ),
        ),
    ]
